[[pages]]
path = "pages/Contracts.py"
name = "Contracts"
icon = "📃"

[[pages]]
path = "pages/Invoices.py"
name = "Invoices"
icon = "📄"

[[pages]]
path = "pages/chat.py"
name = "Chat about Data"
icon = "💬"
