[[pages]]
path = "pages/Contracts.py"
name = "Contracts"
icon = "📃"

[[pages]]
path = "pages/Invoices.py"
name = "Invoices"
icon = "📄"

[[pages]]
path = "pages/invoice_analysis.py"
name = "Invoice Analysis"
icon = "📄"

[[pages]]
path = "pages/contract_analysis.py"
name = "Contract Analysis"
icon = "📄"